cmf_routing_auto:
    persistence:
        phpcr:
            enabled: true
            route_basepath: /app/routes
    mapping:
        resources:
            -
                path: "%kernel.project_dir%/config/cmf_routing_auto.yml"
                type: yaml