doctrine_phpcr:
    session:
        default_session: default
        sessions:
            default:
                backend:
                    type: doctrinedbal
                    logging: true
                    profiling: false
                workspace: default
                username: admin
                password: admin
    odm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        session: default
        mappings:
            App:
                type: annotation
                dir: "%kernel.project_dir%/src/Document"
                prefix: App\Document\
                is_bundle: false
