parameters:
    locale: 'en'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\EntityListener\PageListener:
        tags:
            - { name: doctrine.orm.entity_listener }

    App\DataProvider\:
        resource: '../src/DataProvider/*'
        autoconfigure: false
        tags:
            - { name: 'api_platform.item_data_provider', priority: 1 }

    Doctrine\Bundle\PHPCRBundle\Initializer\GenericInitializer:
        arguments:
            - 'PHPCR Initializer'
            - ["/app/pages", "/app/routes"]
        tags:
            - { name: doctrine_phpcr.initializer }

    # Fix error with cmd doctrine:phpcr:node:dump
    doctrine_phpcr.console_dumper:
        class: PHPCR\Util\Console\Helper\PhpcrConsoleDumperHelper
        public: true

    # Allow for auto-wiring
    Cocur\Slugify\SlugifyInterface:
        alias: 'slugify'
